.pragma library
// English country names by ISO 3166-1 alpha-2 code. Auto-generated from .NET RegionInfo.
// Used to show English country names on the English locale (fork i18n hygiene).
var EN = {
"AD":"Andorra",
"AE":"United Arab Emirates",
"AF":"Afghanistan",
"AG":"Antigua & Barbuda",
"AI":"Anguilla",
"AL":"Albania",
"AM":"Armenia",
"AO":"Angola",
"AR":"Argentina",
"AS":"American Samoa",
"AT":"Austria",
"AU":"Australia",
"AW":"Aruba",
"AX":"Åland Islands",
"AZ":"Azerbaijan",
"BA":"Bosnia & Herzegovina",
"BB":"Barbados",
"BD":"Bangladesh",
"BE":"Belgium",
"BF":"Burkina Faso",
"BG":"Bulgaria",
"BH":"Bahrain",
"BI":"Burundi",
"BJ":"Benin",
"BL":"St. Barthélemy",
"BM":"Bermuda",
"BN":"Brunei",
"BO":"Bolivia",
"BQ":"Bonaire, Sint Eustatius and Saba",
"BR":"Brazil",
"BS":"Bahamas",
"BT":"Bhutan",
"BW":"Botswana",
"BY":"Belarus",
"BZ":"Belize",
"CA":"Canada",
"CC":"Cocos (Keeling) Islands",
"CD":"Congo (DRC)",
"CF":"Central African Republic",
"CG":"Congo",
"CH":"Switzerland",
"CI":"Côte d’Ivoire",
"CK":"Cook Islands",
"CL":"Chile",
"CM":"Cameroon",
"CN":"China",
"CO":"Colombia",
"CR":"Costa Rica",
"CU":"Cuba",
"CV":"Cabo Verde",
"CW":"Curaçao",
"CX":"Christmas Island",
"CY":"Cyprus",
"CZ":"Czechia",
"DE":"Germany",
"DJ":"Djibouti",
"DK":"Denmark",
"DM":"Dominica",
"DO":"Dominican Republic",
"DZ":"Algeria",
"EC":"Ecuador",
"EE":"Estonia",
"EG":"Egypt",
"ER":"Eritrea",
"ES":"Spain",
"ET":"Ethiopia",
"FI":"Finland",
"FJ":"Fiji",
"FK":"Falkland Islands",
"FM":"Micronesia",
"FO":"Faroe Islands",
"FR":"France",
"GA":"Gabon",
"GB":"United Kingdom",
"GD":"Grenada",
"GE":"Georgia",
"GF":"French Guiana",
"GG":"Guernsey",
"GH":"Ghana",
"GI":"Gibraltar",
"GL":"Greenland",
"GM":"Gambia",
"GN":"Guinea",
"GP":"Guadeloupe",
"GQ":"Equatorial Guinea",
"GR":"Greece",
"GT":"Guatemala",
"GU":"Guam",
"GW":"Guinea-Bissau",
"GY":"Guyana",
"HK":"Hong Kong",
"HN":"Honduras",
"HR":"Croatia",
"HT":"Haiti",
"HU":"Hungary",
"ID":"Indonesia",
"IE":"Ireland",
"IL":"Israel",
"IM":"Isle of Man",
"IN":"India",
"IO":"British Indian Ocean Territory",
"IQ":"Iraq",
"IR":"Iran",
"IS":"Iceland",
"IT":"Italy",
"JE":"Jersey",
"JM":"Jamaica",
"JO":"Jordan",
"JP":"Japan",
"KE":"Kenya",
"KG":"Kyrgyzstan",
"KH":"Cambodia",
"KI":"Kiribati",
"KM":"Comoros",
"KN":"St. Kitts & Nevis",
"KP":"North Korea",
"KR":"South Korea",
"KW":"Kuwait",
"KY":"Cayman Islands",
"KZ":"Kazakhstan",
"LA":"Laos",
"LB":"Lebanon",
"LC":"St. Lucia",
"LI":"Liechtenstein",
"LK":"Sri Lanka",
"LR":"Liberia",
"LS":"Lesotho",
"LT":"Lithuania",
"LU":"Luxembourg",
"LV":"Latvia",
"LY":"Libya",
"MA":"Morocco",
"MC":"Monaco",
"MD":"Moldova",
"ME":"Montenegro",
"MF":"St. Martin",
"MG":"Madagascar",
"MH":"Marshall Islands",
"MK":"North Macedonia",
"ML":"Mali",
"MM":"Myanmar",
"MN":"Mongolia",
"MO":"Macau",
"MP":"Northern Mariana Islands",
"MQ":"Martinique",
"MR":"Mauritania",
"MS":"Montserrat",
"MT":"Malta",
"MU":"Mauritius",
"MV":"Maldives",
"MW":"Malawi",
"MX":"Mexico",
"MY":"Malaysia",
"MZ":"Mozambique",
"NA":"Namibia",
"NC":"New Caledonia",
"NE":"Niger",
"NF":"Norfolk Island",
"NG":"Nigeria",
"NI":"Nicaragua",
"NL":"Netherlands",
"NO":"Norway",
"NP":"Nepal",
"NR":"Nauru",
"NU":"Niue",
"NZ":"New Zealand",
"OM":"Oman",
"PA":"Panama",
"PE":"Peru",
"PF":"French Polynesia",
"PG":"Papua New Guinea",
"PH":"Philippines",
"PK":"Pakistan",
"PL":"Poland",
"PM":"St. Pierre & Miquelon",
"PN":"Pitcairn Islands",
"PR":"Puerto Rico",
"PS":"Palestinian Authority",
"PT":"Portugal",
"PW":"Palau",
"PY":"Paraguay",
"QA":"Qatar",
"RE":"Réunion",
"RO":"Romania",
"RS":"Serbia",
"RU":"Russia",
"RW":"Rwanda",
"SA":"Saudi Arabia",
"SB":"Solomon Islands",
"SC":"Seychelles",
"SD":"Sudan",
"SE":"Sweden",
"SG":"Singapore",
"SH":"St Helena, Ascension, Tristan da Cunha",
"SI":"Slovenia",
"SJ":"Svalbard & Jan Mayen",
"SK":"Slovakia",
"SL":"Sierra Leone",
"SM":"San Marino",
"SN":"Senegal",
"SO":"Somalia",
"SR":"Suriname",
"SS":"South Sudan",
"ST":"São Tomé & Príncipe",
"SV":"El Salvador",
"SX":"Sint Maarten",
"SY":"Syria",
"SZ":"Eswatini",
"TC":"Turks & Caicos Islands",
"TD":"Chad",
"TG":"Togo",
"TH":"Thailand",
"TJ":"Tajikistan",
"TK":"Tokelau",
"TL":"Timor-Leste",
"TM":"Turkmenistan",
"TN":"Tunisia",
"TO":"Tonga",
"TR":"Turkey",
"TT":"Trinidad & Tobago",
"TV":"Tuvalu",
"TW":"Taiwan",
"TZ":"Tanzania",
"UA":"Ukraine",
"UG":"Uganda",
"UM":"U.S. Outlying Islands",
"US":"United States",
"UY":"Uruguay",
"UZ":"Uzbekistan",
"VA":"Vatican City",
"VC":"St. Vincent & Grenadines",
"VE":"Venezuela",
"VG":"British Virgin Islands",
"VI":"U.S. Virgin Islands",
"VN":"Vietnam",
"VU":"Vanuatu",
"WF":"Wallis & Futuna",
"WS":"Samoa",
"XK":"Kosovo",
"YE":"Yemen",
"YT":"Mayotte",
"ZA":"South Africa",
"ZM":"Zambia",
"ZW":"Zimbabwe"
};
function en(code){ var cc = ("" + code).toUpperCase(); var n = EN[cc]; return (n && n.length) ? n : ""; }
function localName(code, fallback, isEng){ if(isEng){ var e = en(code); if(e.length) return e; } return fallback ? ("" + fallback) : ""; }
var RU = {
"FI":"Финляндия","DE":"Германия","NL":"Нидерланды","SE":"Швеция","FR":"Франция",
"GB":"Великобритания","US":"США","PL":"Польша","LT":"Литва","LV":"Латвия",
"EE":"Эстония","CH":"Швейцария","AT":"Австрия","ES":"Испания","IT":"Италия",
"NO":"Норвегия","DK":"Дания","CZ":"Чехия","RO":"Румыния","BG":"Болгария",
"TR":"Турция","UA":"Украина","KZ":"Казахстан","AM":"Армения","GE":"Грузия",
"RS":"Сербия","MD":"Молдова","HU":"Венгрия","IE":"Ирландия","PT":"Португалия",
"BE":"Бельгия","LU":"Люксембург","JP":"Япония","SG":"Сингапур","HK":"Гонконг",
"CA":"Канада","AE":"ОАЭ","IL":"Израиль","IN":"Индия","AU":"Австралия","ZA":"ЮАР",
"BR":"Бразилия","KR":"Южная Корея","CY":"Кипр","MT":"Мальта","IS":"Исландия","RU":"Россия"
};
var _nameIndex = null;
function _buildNameIndex(){
    var out = [];
    for (var code in RU) {
        var r = RU[code];
        if (r && r.length) { out.push([r.toUpperCase(), code]); }
        var e = EN[code];
        if (e && e.length) { out.push([e.toUpperCase(), code]); }
    }
    out.sort(function(a, b){ return b[0].length - a[0].length; });
    return out;
}
function codeFromName(name){
    var n = ("" + name).toUpperCase();
    if (n.length === 0) { return ""; }
    if (_nameIndex === null) { _nameIndex = _buildNameIndex(); }
    for (var i = 0; i < _nameIndex.length; i++) {
        if (n.indexOf(_nameIndex[i][0]) >= 0) { return _nameIndex[i][1]; }
    }
    return "";
}